#!/usr/bin/env php
<?php

define('NO_AGENT_CHECK', true);
define('DisableEventsCheck', true);
define('NO_KEEP_STATISTIC', true);
define('NO_AGENT_STATISTIC', true);
define('NOT_CHECK_PERMISSIONS', true);
define('STOP_STATISTICS', true);

use Bitrix\Main\Loader;
use Bx\Model\Gen\Commands\GenerateHlBlock;
use Bx\Model\Gen\Commands\GenerateIblock;
use Bx\Model\Gen\Commands\GenerateTable;
use Symfony\Component\Console\Application;

if (file_exists(__DIR__ . '/vendor/autoload.php')) {
    require_once __DIR__ . '/vendor/autoload.php';
} elseif (file_exists(__DIR__ . '/local/vendor/autoload.php')) {
    require_once __DIR__ . '/local/vendor/autoload.php';
} elseif (file_exists(__DIR__ . '/local/modules/bx.model.gen/vendor/autoload.php')) {
    require_once __DIR__ . '/local/modules/bx.model.gen/vendor/autoload.php';
}

$_SERVER["DOCUMENT_ROOT"] = __DIR__;
require $_SERVER["DOCUMENT_ROOT"]."/bitrix/modules/main/include/prolog_before.php";

Loader::includeModule('bx.model.gen');

$app = new Application('Bitrix model generator', '0.0.1');
$app->add(new GenerateIblock());
$app->add(new GenerateTable());
$app->add(new GenerateHlBlock());

$app->run();