#!/usr/bin/env php
<?php

define('NO_AGENT_CHECK', true);
define('DisableEventsCheck', true);
define('NO_KEEP_STATISTIC', true);
define('NO_AGENT_STATISTIC', true);
define('NOT_CHECK_PERMISSIONS', true);
define('STOP_STATISTICS', true);

use Bitrix\Main\Loader;
use Bx\Model\Gen\AppFactory;

$_SERVER["DOCUMENT_ROOT"] = __DIR__;
require $_SERVER["DOCUMENT_ROOT"]."/bitrix/modules/main/include/prolog_before.php";

if (file_exists(__DIR__ . '/vendor/autoload.php')) {
    require_once __DIR__ . '/vendor/autoload.php';
} elseif (file_exists(__DIR__ . '/local/vendor/autoload.php')) {
    require_once __DIR__ . '/local/vendor/autoload.php';
} elseif (file_exists(__DIR__ . '/local/modules/bx.model.gen/vendor/autoload.php')) {
    require_once __DIR__ . '/local/modules/bx.model.gen/vendor/autoload.php';
}

Loader::includeModule('bx.model.gen');
AppFactory::create()->run();